### PR TITLE
Migrate tests mocking to fetch API

### PR DESCRIPTION
**Pull request by alshakero**
Requires releasing a version from https://github.com/Palindrom/Palindrom/pull/227

### CODE REVIEW

**Comment by warpech** [comment]
I need some background, does `palindrom-client` stop working if we release https://github.com/Palindrom/palindrom-client/pull/83 but don't include this change in `palindrom-client`?

Is this the only change needed in `palindrom-client`?

**Comment by alshakero** [comment]
> I need some background, does palindrom-client stop working if we release #83 but don't include this change in palindrom-client?

TBH, I don't understand this question. 

---

There are no needed changes in `palindrom-client` functionality-wise. The only needed change is migrating the tests to mock `fetch` API instead of `XHR`. As in, if someone assumingly doesn't update `palindrom-client` in their app but manages to update Palindrom to the upcoming `fetch` version, their app would continue working just fine.

> Is this the only change needed in palindrom-client?

Yes

**Comment by warpech** [comment]
Thanks, you answered my question :)

**Comment by warpech** [comment]
The priority of this PR is super-low, because we are no longer putting ephasis on using Palindrom + Polymer. Integrating with more frameworks should have a higher priority

**Pull request merged**
